version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: pulsar-proxy-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
      - ./valkey.conf:/etc/valkey/valkey.conf:ro
    command: valkey-server /etc/valkey/valkey.conf
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - proxy-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulsar-proxy
    ports:
      - "8080:8080"  # HTTP API
      - "8081:8081"  # WebSocket
      - "9090:9090"  # Metrics
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - VALKEY_PASSWORD=changeme
      - LOG_LEVEL=info
    depends_on:
      valkey:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - proxy-network

  prometheus:
    image: prom/prometheus:latest
    container_name: pulsar-proxy-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - proxy-network

  grafana:
    image: grafana/grafana:latest
    container_name: pulsar-proxy-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - proxy-network

volumes:
  valkey-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  proxy-network:
    driver: bridge
